FROM python:3.10

RUN mkdir -p /app/School-days-grupo3-eng-sw-unifesp
WORKDIR /app
VOLUME /app/School-days-grupo3-eng-sw-unifesp

RUN pip install --upgrade pip
RUN pip install django==5.0
RUN git clone https://github.com/asbmails2/School-days-grupo3-eng-sw-unifesp.git
RUN cd ./School-days-grupo3-eng-sw-unifesp
RUN git init 
RUN git add .

#para rodar o container e manter a pasta de arquivos alterados 
#pode usar o comando abaixo 
# $ docker run -d -i -v ./School:/app/School-days-grupo3-eng-sw-unifesp schooldays
# ou também por meio do código
# $ docker run -d -i -p 8000:8000 schooldays