FROM python:3.10

WORKDIR /app

COPY requiriments.txt .
RUN pip install requiriments.txt

#DJANGO HowTo

#1 Clonar o repositório:

RUN git clone git@github.com:asbmails2/School-days-grupo3-eng-sw-unifesp.git

RUN cd School-days-grupo3-eng-sw-unifesp/

#2 Instalar [ambiente virtual Python](https://docs.python.org/3/library/venv.html) e o framework [Django](https://www.djangoproject.com/):

RUN python -m venv venv

RUN source venv/bin/activate

RUN pip install django==5.0

RUN python -m django --version 5.0

CMD ["python", "manage.py", "runserver"]

