# Generated by Django 5.0.3 on 2024-06-25 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0002_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Disciplina')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código da Disciplina')),
                ('carga_horaria', models.IntegerField(verbose_name='Horas Aula')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Turma', to='pessoas.professor', verbose_name='Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='nome da turma')),
                ('ano_ocorrencia', models.IntegerField(verbose_name='Ano de Ocorrência')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('alunos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.aluno')),
                ('disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoas.aluno')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.disciplina')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.turma')),
            ],
        ),
    ]
